name: flutter_joybuttons
description: Virtual buttons for Flutter touchscreen applications. Flexible and customizable.
version: 1.0.1
homepage: https://github.com/cybaker/flutter_joybuttons
repository: https://github.com/cybaker/flutter_joybuttons

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  test: ^1.21.1

flutter:
  uses-material-design: true
