name: Publish to GitHub Pages and pub.dev

on:
  push:
    branches: [ main ]
    tags:
      # For pub.dev publishing. Must align with the tag-pattern configured on pub.dev
      - 'v[0-9]+.[0-9]+.[0-9]+*' # tag-pattern on pub.dev: 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
      - run: flutter pub get

      - name: Run unit tests
      - run: flutter test

      - name: Publish example web pages
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /flutter_joybuttons/
          workingDir: example

  publish:
    name: Publish to pub.dev
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1