name: Publish to GitHub Pages and pub.dev

on:
  push:
    branches: [ main ]
    tags:
      # For pub.dev publishing. Must align with the tag-pattern configured on pub.dev
      - 'v[0-9]+.[0-9]+.[0-9]+*' # tag-pattern on pub.dev: 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
      - run: flutter pub get
      - run: flutter test
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /flutter_joybuttons/
          workingDir: example

  publish:
    # For pub.dev publishing.
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1